# Generated by Django 5.2.2 on 2025-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_category_comment_delete_news_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an article image",
                null=True,
                upload_to="article_images/",
            ),
        ),
    ]
